@startuml C4_Contexto_Consultas_Medicas

!include <C4/C4_Context>


SHOW_LEGEND()

System_Boundary(c1, "Sistema de Gerenciamento de Consultas Médicas") {

  Person(paciente, "Paciente", "Agenda consultas, visualiza histórico")
  Person(medico, "Médico", "Gerencia agenda, adiciona observações em consultas")
  Person(admin, "Administrador", "Gerencia o sistema, adiciona médicos, supervisiona consultas e horários")

  System(frontend, "Frontend", "Interface web para pacientes, médicos e administradores")
  SystemDb(banco_dados, "Banco de Dados", "Armazena informações de pacientes, médicos, consultas, horários e administradores")
  System(backend, "Backend", "API REST para gerenciar consultas, autenticação e lógica de negócios")

}

Rel(paciente, frontend, "Acessa", "HTTPS")
Rel(medico, frontend, "Acessa", "HTTPS")
Rel(admin, frontend, "Acessa", "HTTPS")
Rel(frontend, backend, "Utiliza API", "HTTPS")
Rel(backend, banco_dados, "Lê e escreve dados", "JDBC")

SHOW_LEGEND()

@enduml