@startuml
skinparam rectangle {
    BackgroundColor LightBlue
}

title Context Diagram

actor User
rectangle "Sistema Médico" {
    rectangle "Frontend (NextJS)" as NextJS
    rectangle "Backend (FastAPI)" as FastAPIApp
    database "PostgreSQL" as PostgreSQL
}

User --> NextJS : Uses
NextJS --> FastAPIApp : Uses
FastAPIApp --> PostgreSQL : Uses

@enduml